internal static partial class LauncherTools
{
    sealed record InventoryPlan(System.Text.Json.Nodes.JsonObject State,long[] Clothes,long[] Pets,System.Collections.Generic.Dictionary<long,(long Upgrade,long[] Gems)> PetValues);
    static InventoryPlan ValidateInventory(System.Text.Json.Nodes.JsonObject state,IEnumerable<System.Text.Json.Nodes.JsonObject> originalCards)
    {
        state=(System.Text.Json.Nodes.JsonObject)Clone(state);var shop=state["shop"]??throw new InvalidDataException("Missing shop");var equip=A(shop,"equipped").Select(x=>Num(x)).ToArray();Require(equip.Length==5,"profile needs five equipment slots");
        var clothes=A(state,"clothing").Select(x=>Num(x)).Where(x=>x!=0).Concat(equip).Append(N(shop,"effect")).Where(x=>x!=0).Distinct().ToArray();
        var pets=Objects(state,"pets").Select(x=>N(x,"code")).Append(N(shop,"selected_pet")).Where(x=>x!=0).Distinct().ToArray();Require(clothes.Length<=256&&pets.Length<=128,"inventory capacity exceeded");Require(clothes.All(Catalog["clothing"].ContainsKey),"unknown clothing");Require(pets.All(Catalog["pets"].ContainsKey),"unknown pet");
        var petValues=new Dictionary<long,(long,long[])>();var petRows=Objects(state,"pets").ToDictionary(x=>N(x,"code"));foreach(var code in pets){var meta=Catalog["pets"][code];petRows.TryGetValue(code,out var row);var gems=A(row,"gems").Take(3).Select(x=>Num(x)).Concat(new long[3]).Take(3).ToArray();for(int i=0;i<3;i++){if(i>=N(meta,"slot_count"))gems[i]=0;else Require(gems[i]==0||Catalog["gems"].ContainsKey(gems[i]),"unknown pet gem");}var upgrade=N(row,"upgrade_material");Require(upgrade==0||upgrade==N(meta,"upgrade_material"),"invalid upgrade material");petValues[code]=(upgrade,gems);}
        var games=Objects(state,"game_items").ToArray();Require(games.Select(x=>N(x,"code")).Distinct().Count()==games.Length,"duplicate game item code");foreach(var row in games)Require(Catalog["game"].ContainsKey(N(row,"code"))&&N(row,"count") is >=1 and <=65535,"invalid game item/count");
        var protectedCards=originalCards.Where(x=>!Catalog["cards"].ContainsKey(N(x,"code"))).ToDictionary(x=>N(x,"code"),x=>N(x,"count"));var cards=new System.Text.Json.Nodes.JsonArray();var seen=new HashSet<long>();foreach(var row in Objects(state,"cards")){long code=N(row,"code"),count=N(row,"count");Require(seen.Add(code),"duplicate card code");if(Catalog["cards"].ContainsKey(code)){Require(count is >=1 and <=255,"card count out of range");cards.Add(Obj(new{code,count}));}else Require(protectedCards.TryGetValue(code,out var old)&&old==count,"uncatalogued card is read-only; cannot add or change its stored quantity");}foreach(var(code,count) in protectedCards.OrderBy(x=>x.Key))cards.Add(Obj(new{code,count}));state["cards"]=cards;
        var furniture=Objects(state,"furniture").ToArray();Require(furniture.Length<=254&&furniture.Count(x=>B(x,"placed"))<=84,"furniture capacity exceeded");var indices=new HashSet<long>();foreach(var row in furniture){var code=N(row,"code");Require(Catalog["furniture"].ContainsKey(code),"unknown furniture");var index=N(row,"index");if(index<=0)index=Enumerable.Range(1,254).FirstOrDefault(i=>!indices.Contains(i));Require(index is >=1 and <=254&&indices.Add(index)&&(!B(row,"placed")||index<=84),"invalid/duplicate furniture index");Require(N(row,"x",400) is >=-32768 and <=32767&&N(row,"y",300) is >=-32768 and <=32767&&N(row,"z") is >=0 and <=255&&N(row,"mirror") is 0 or 1,"invalid furniture placement");row["index"]=index;row["type"]=N(Catalog["furniture"][code],"type");}
        Require(N(shop,"coin")>=0&&N(shop,"nana")>=0,"currency out of range");state["clothing"]=Arr(clothes.Cast<object>());state["pets"]=Arr(pets.Select(code=>(object)Obj(new{code,upgrade_material=petValues[code].Item1,gems=petValues[code].Item2})));return new(state,clothes,pets,petValues);
    }
    static System.Text.Json.Nodes.JsonObject Apply(string hex,System.Text.Json.Nodes.JsonObject state,long? id,System.Text.Json.Nodes.JsonObject? copySource=null)
    {
        if(id is null&&copySource is null){var name=ValidateHex(hex);var rows=Profiles("");var match=rows.Where(r=>r?["account_id"] is not null&&S(r,"username").Equals(name,StringComparison.OrdinalIgnoreCase)).ToArray();if(match.Length==0)match=rows.Where(r=>r?["character_id"] is not null&&S(r,"character_name").Equals(name,StringComparison.OrdinalIgnoreCase)).ToArray();Require(match.Length<=1,"ambiguous database profile identity");if(match.Length==1){Require(match[0]!["character_id"] is not null,"selected account has no character yet");id=N(match[0],"character_id");}}
        if(id is not null)return DbApply(id.Value,state);
        var path=DraftPath(hex);var existing=copySource??Snapshot(hex,null);var plan=ValidateInventory(state,Objects(existing,"cards"));state=plan.State;state["version"]=2;state["source"]="sidecar";state["character_id"]=null;state["name_hex"]=hex;state["account_suffix"]="p_"+hex;state["profile"]??=new System.Text.Json.Nodes.JsonObject();state["profile"]!["character_name"]=ValidateHex(hex);state["profile"]!["coin"]=N(state["shop"],"coin");state["profile"]!["nana_point"]=N(state["shop"],"nana");
        // A draft is a DB record, not a second set of global DAT ledgers.
        Store.Read(path);string? sourcePath=copySource is not null&&S(copySource,"source")=="sidecar"?DraftPath(S(copySource,"name_hex")):null;var saveSource=sourcePath is not null&&Store.Read(sourcePath) is null;
        var backup=Store.Backup(Path.Combine(Root,"inventory_admin_backups"));using var c=Store.Open();using var t=c.BeginTransaction(deferred:false);
        if(copySource is not null){var key=OpenNanaimo.Adapter.Services.PersistentStateStore.Key(path,Db);Require(Rows(c,t,"SELECT 1 FROM NativeState WHERE Scope=$scope AND Name=$name AND Content IS NOT NULL",("$scope",key.Scope),("$name",key.Name)).Count==0,"target profile already exists; select it instead");}
        if(Rows(c,t,"SELECT 1 FROM sqlite_master WHERE name='Characters' AND type='table'").Count>0)
            Require(Rows(c,t,"SELECT c.Id FROM Characters c JOIN Accounts a ON a.Id=c.AccountId WHERE a.Username=$name COLLATE NOCASE OR c.Name=$name COLLATE NOCASE",("$name",ValidateHex(hex))).Count==0,"Profile was registered while saving; reload the database character before retrying");
        if(saveSource)OpenNanaimo.Adapter.Services.PersistentStateStore.Write(c,t,sourcePath!,System.Text.Encoding.UTF8.GetBytes(copySource!.ToJsonString()));
        OpenNanaimo.Adapter.Services.PersistentStateStore.Write(c,t,path,System.Text.Encoding.UTF8.GetBytes(state.ToJsonString()));t.Commit();return Obj(new{source="database-draft",account_suffix="p_"+hex,backup,files=new[]{Db}});
    }
    static System.Text.Json.Nodes.JsonObject DbApply(long id,System.Text.Json.Nodes.JsonObject state)
    {
        var backup=BackupDb();using var c=OpenDb();var cols=Columns(c,"Characters");var itemCols=Columns(c,"CharacterItems");using var t=c.BeginTransaction(deferred:false);
        var rows=Rows(c,t,"SELECT c.*,a.IsOnline account_online FROM Characters c JOIN Accounts a ON a.Id=c.AccountId WHERE c.Id=$id",("$id",id));Require(rows.Count==1,"selected character profile no longer exists");var current=rows[0];Require(V(current,"IsOnline")==0&&V(current,"account_online")==0,"selected user is online; stop clients and adapter before editing");
        var oldCards=Rows(c,t,"SELECT CardCode,Quantity FROM CharacterCards WHERE CharacterId=$id",("$id",id)).Select(x=>Obj(new{code=V(x,"CardCode"),count=V(x,"Quantity")}));var plan=ValidateInventory(state,oldCards);state=plan.State;var profile=state["profile"]??new System.Text.Json.Nodes.JsonObject();var shop=state["shop"]!;var now=DateTime.UtcNow.ToString("O");var updates=new Dictionary<string,object?>{{"Hans",N(shop,"coin")},{"Cash",N(shop,"nana")}};
        foreach(var(key,col) in ProfileFields)if(cols.Contains(col)&&profile[key] is not null){long value=N(profile,key);Require(value>=0&&value<=(col is "MaxHp" or "MaxMp" or "DefenseFlat"?65535:col=="AttackModifier"?1000000:uint.MaxValue),"profile value out of range: "+key);updates[col]=value;}
        foreach(var(which,column,currentCol) in new[]{("hp","MaxHp","CurrentHp"),("mp","MaxMp","CurrentMp")})if(updates.TryGetValue(column,out var max)&&cols.Contains(currentCol)){var v=N(profile,which+"_current",Convert.ToInt64(max));Require(v>=0,"negative current resource");updates[currentCol]=Math.Min(v,Convert.ToInt64(max));}
        if(profile["skill_slot_z"] is not null||profile["skill_slot_x"] is not null||Enumerable.Range(0,16).Any(i=>profile["skill_grade"+i] is not null))
        {
            Require(cols.Contains("SelectedSkill0")&&cols.Contains("SelectedSkill1"),"database skill schema is missing");var grades=new long[16];foreach(var row in Rows(c,t,"SELECT SkillCode,Grade FROM CharacterSkills WHERE CharacterId=$id",("$id",id))){var i=V(row,"SkillCode")-52000000;if(i is >=0 and <16)grades[i]=V(row,"Grade");}for(int i=0;i<16;i++){grades[i]=N(profile,"skill_grade"+i,grades[i]);Require(grades[i] is >=0 and <=5,"skill grade must be 0..5");}foreach(int start in new[]{0,8})Require(!new[]{2,4,6}.Any(i=>grades[start+i]>0)||!new[]{3,5,7}.Any(i=>grades[start+i]>0),"conflicting skill branches");
            long z=N(profile,"skill_slot_z",V(current,"SelectedSkill0")),x=N(profile,"skill_slot_x",V(current,"SelectedSkill1"));foreach(var code in new[]{z,x})Require(code==0||code is >=52000000 and <52000016&&grades[code-52000000]>0,"selected skill is not learned");Require(z==0||z!=x,"Z and X must be different skills");updates["SelectedSkill0"]=z;updates["SelectedSkill1"]=x;
            for(int i=0;i<16;i++)if(profile["skill_grade"+i] is not null){if(grades[i]>0)Exec(c,t,"INSERT INTO CharacterSkills(CharacterId,SkillCode,Grade,UpdatedAt) VALUES($id,$code,$grade,$now) ON CONFLICT(CharacterId,SkillCode) DO UPDATE SET Grade=excluded.Grade,UpdatedAt=excluded.UpdatedAt",("$id",id),("$code",52000000+i),("$grade",grades[i]),("$now",now));else Exec(c,t,"DELETE FROM CharacterSkills WHERE CharacterId=$id AND SkillCode=$code",("$id",id),("$code",52000000+i));}
        }
        if(B(profile,"skill_slot_expiry_apply")){long expiry=N(profile,"skill_slot_expiry");Require(expiry==0||expiry is >=2000010100 and <=2100123123&&DateTime.TryParseExact(expiry.ToString(),"yyyyMMddHH",System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out _),"invalid Z/X slot expiry");Require(cols.Contains("SkillSlotExpansionExpires"),"missing skill expiry schema");updates["SkillSlotExpansionExpires"]=expiry;}
        var appearance=current["Appearance"] as byte[]??[];if(appearance.Length<36)Array.Resize(ref appearance,36);var equipped=A(shop,"equipped").Select(v=>Num(v)).ToArray();foreach(var(offset,code) in new[]{0,4,8,12,20}.Zip(equipped))System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(appearance.AsSpan(offset),checked((uint)code));long selected=N(shop,"selected_pet");System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(appearance.AsSpan(24),checked((uint)N(shop,"effect")));System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(appearance.AsSpan(28),checked((uint)selected));System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(appearance.AsSpan(32),checked((uint)V(current,"Gender")));updates["Appearance"]=appearance;updates["EquippedPetItemCode"]=selected;if(cols.Contains("LastSavedAt"))updates["LastSavedAt"]=now;
        Update(c,t,"Characters",updates,"Id",id);
        var games=Objects(state,"game_items").ToArray();var furniture=Objects(state,"furniture").ToArray();var retained=plan.Clothes.Concat(plan.Pets).Concat(games.Select(x=>N(x,"code"))).Concat(furniture.Select(x=>N(x,"code"))).ToHashSet();var editable=new[]{"clothing","pets","game","furniture"}.SelectMany(k=>Catalog[k].Keys).ToHashSet();foreach(var row in Rows(c,t,"SELECT ItemCode FROM CharacterItems WHERE CharacterId=$id",("$id",id))){long code=V(row,"ItemCode");if(editable.Contains(code)&&!retained.Contains(code))Exec(c,t,"DELETE FROM CharacterItems WHERE CharacterId=$id AND ItemCode=$code",("$id",id),("$code",code));}
        void Item(long code,long qty,Dictionary<string,object?>? extra=null){var values=new Dictionary<string,object?>{{"CharacterId",id},{"ItemCode",code},{"Quantity",qty},{"UpdatedAt",now}};if(extra is not null)foreach(var(k,v) in extra)if(itemCols.Contains(k))values[k]=v;var names=values.Keys.ToArray();var mutable=names.Except(new[]{"CharacterId","ItemCode","UpdatedAt"});Exec(c,t,"INSERT INTO CharacterItems("+string.Join(',',names)+") VALUES("+string.Join(',',names.Select(k=>"$"+k))+") ON CONFLICT(CharacterId,ItemCode) DO UPDATE SET "+string.Join(',',mutable.Select(k=>k+"=excluded."+k)),values.Select(x=>("$"+x.Key,x.Value)).ToArray());}
        foreach(var code in plan.Clothes)Item(code,1);
        foreach(var code in plan.Pets){var(upgrade,gems)=plan.PetValues[code];var extra=new Dictionary<string,object?>{{"PetAccessory0",gems[0]},{"PetAccessory1",gems[1]},{"PetAccessory2",gems[2]}};if(itemCols.Contains("PetCurrentStage")){var old=Rows(c,t,"SELECT PetCurrentStage FROM CharacterItems WHERE CharacterId=$id AND ItemCode=$code",("$id",id),("$code",code));var stage=old.Count>0?V(old[0],"PetCurrentStage"):0;extra["PetCurrentStage"]=upgrade==(stage>0?N(Catalog["pets"][code],"upgrade_material"):0)?stage:upgrade>0?1:0;}Item(code,1,extra);}
        var petProgress=new Dictionary<string,object?>();foreach(var col in new[]{"PetLevel","PetExperience"})if(cols.Contains(col)){var old=itemCols.Contains(col)?Rows(c,t,"SELECT "+col+" FROM CharacterItems WHERE CharacterId=$id AND ItemCode=$code",("$id",id),("$code",selected)):[];petProgress[col]=old.Count>0?V(old[0],col):0;}if(petProgress.Count>0)Update(c,t,"Characters",petProgress,"Id",id);
        foreach(var row in games)Item(N(row,"code"),N(row,"count"));foreach(var group in furniture.GroupBy(x=>N(x,"code")))Item(group.Key,group.Count());
        foreach(var row in Rows(c,t,"SELECT CardCode FROM CharacterCards WHERE CharacterId=$id",("$id",id)))if(Catalog["cards"].ContainsKey(V(row,"CardCode")))Exec(c,t,"DELETE FROM CharacterCards WHERE CharacterId=$id AND CardCode=$code",("$id",id),("$code",V(row,"CardCode")));
        foreach(var row in Objects(state,"cards"))if(Catalog["cards"].ContainsKey(N(row,"code")))Exec(c,t,"INSERT INTO CharacterCards(CharacterId,CardCode,Quantity,UpdatedAt) VALUES($id,$code,$qty,$now)",("$id",id),("$code",N(row,"code")),("$qty",N(row,"count")),("$now",now));
        Exec(c,t,"DELETE FROM CharacterApartmentItems WHERE CharacterId=$id",("$id",id));foreach(var row in furniture.Where(x=>B(x,"placed")))Exec(c,t,"INSERT INTO CharacterApartmentItems(CharacterId,SlotIndex,ItemCode,PositionX,PositionY,Layer,Mirror,InteriorType,UpdatedAt) VALUES($id,$slot,$code,$x,$y,$z,$mirror,$type,$now)",("$id",id),("$slot",N(row,"index")-1),("$code",N(row,"code")),("$x",N(row,"x",400)),("$y",N(row,"y",300)),("$z",N(row,"z")),("$mirror",N(row,"mirror")),("$type",N(row,"type")),("$now",now));
        t.Commit();return Obj(new{source="database",character_id=id,backup,files=new[]{Db}});
    }
    static string BackupDb()
    {
        Require(File.Exists(Db),"database is missing");var directory=Path.Combine(Root,"inventory_admin_backups",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var path=Path.Combine(directory,"game.db");using var source=OpenDb();using var destination=new Microsoft.Data.Sqlite.SqliteConnection(new Microsoft.Data.Sqlite.SqliteConnectionStringBuilder{DataSource=path,Pooling=false}.ToString());destination.Open();source.BackupDatabase(destination);return path;
    }
    static void Update(Microsoft.Data.Sqlite.SqliteConnection c,Microsoft.Data.Sqlite.SqliteTransaction t,string table,Dictionary<string,object?> values,string idColumn,long id)=>Exec(c,t,"UPDATE "+table+" SET "+string.Join(',',values.Keys.Select(k=>k+"=$"+k))+" WHERE "+idColumn+"=$id",values.Select(x=>("$"+x.Key,x.Value)).Append(("$id",(object?)id)).ToArray());
}
