using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

if (args.Length != 3)
{
    Console.Error.WriteLine("Usage: CombatScoreGenerator <dungeon_combat_catalog.bin> <hp_resource_global_data.inc> <output.inc>");
    return 2;
}

var catalogPath = Path.GetFullPath(args[0]);
var hpDataPath = Path.GetFullPath(args[1]);
var outputPath = Path.GetFullPath(args[2]);
var catalog = ReadCatalog(catalogPath);
var hpData = ReadHpData(hpDataPath, catalog.RuntimeScores);

if (hpData.MatchedRuntimeKeys.Count != catalog.RuntimeScores.Count)
{
    var missing = catalog.RuntimeScores.Keys.Except(hpData.MatchedRuntimeKeys).Take(5).ToArray();
    throw new InvalidDataException(
        $"Only {hpData.MatchedRuntimeKeys.Count}/{catalog.RuntimeScores.Count} DCC7 runtime score keys matched HP targets. " +
        $"First missing: {string.Join(", ", missing)}");
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
var tempPath = outputPath + ".tmp";
using (var writer = new StreamWriter(tempPath, false, new UTF8Encoding(false), 1 << 20))
{
    writer.WriteLine("/* Generated by scripts/combat-score-generator from DCC7; do not hand-edit. */");
    writer.WriteLine("#ifndef NANAIMO_COMBAT_SCORE_RESOURCE_DATA_INC");
    writer.WriteLine("#define NANAIMO_COMBAT_SCORE_RESOURCE_DATA_INC");
    writer.WriteLine($"#define COMBAT_SCORE_DCC7_SHA256 \"{Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(catalogPath)))}\"");
    writer.WriteLine($"#define COMBAT_SCORE_HP_TABLE_SHA256 \"{Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(hpDataPath)))}\"");
    writer.WriteLine($"#define COMBAT_SCORE_TARGET_COUNT {hpData.TargetScores.Count}u");
    writer.WriteLine($"#define COMBAT_SCORE_PROFILE_COUNT {hpData.Profiles.Count}u");
    writer.WriteLine("struct combat_score_profile_def { unsigned char hd,episode,dungeon,stage_index,slot,reserved0,reserved1,reserved2; unsigned hit_max,boss_bonus,total_max; };");
    writer.WriteLine("static const unsigned combat_score_target_scores[COMBAT_SCORE_TARGET_COUNT]={");
    for (var index = 0; index < hpData.TargetScores.Count; index += 16)
    {
        writer.Write(' ');
        var end = Math.Min(index + 16, hpData.TargetScores.Count);
        for (var item = index; item < end; item++)
        {
            if (item != index)
                writer.Write(',');
            writer.Write(hpData.TargetScores[item].ToString(CultureInfo.InvariantCulture));
            writer.Write('u');
        }
        writer.WriteLine(',');
    }
    writer.WriteLine("};");
    writer.WriteLine("static const struct combat_score_profile_def combat_score_profiles[COMBAT_SCORE_PROFILE_COUNT]={");
    foreach (var profile in hpData.Profiles)
    {
        var key = profile.Key;
        var hitMax = hpData.EffectiveHitMaximums.GetValueOrDefault(key);
        var bossBonus = catalog.BossBonuses.GetValueOrDefault(key);
        var totalMax = checked(hitMax + bossBonus);
        writer.WriteLine($" {{{key.Hd},{key.Episode},{key.Dungeon},{key.Stage},{key.Slot},0,0,0,{hitMax}u,{bossBonus}u,{totalMax}u}},");
    }
    writer.WriteLine("};");
    writer.WriteLine("#endif");
}
File.Move(tempPath, outputPath, true);

Console.WriteLine(
    $"COMBAT_SCORE_GENERATION_PASS targets={hpData.TargetScores.Count} profiles={hpData.Profiles.Count} " +
    $"runtime={catalog.RuntimeScores.Count} matched={hpData.MatchedRuntimeKeys.Count} " +
    $"positive={hpData.TargetScores.Count(score => score > 0)} distinct={hpData.TargetScores.Distinct().Count()} " +
    $"bossProfiles={catalog.BossBonuses.Count(pair => pair.Value > 0)} output={outputPath}");
return 0;

static CatalogData ReadCatalog(string path)
{
    using var stream = File.OpenRead(path);
    using var reader = new BinaryReader(stream, Encoding.ASCII, leaveOpen: false);
    if (!reader.ReadBytes(4).AsSpan().SequenceEqual("DCC7"u8))
        throw new InvalidDataException($"Invalid DCC7 signature: {path}");

    var normalCount = ReadCount(reader, "normal");
    for (var index = 0; index < normalCount; index++)
    {
        ReadKey(reader);
        ReadTemplate(reader);
    }

    var bossCount = ReadCount(reader, "boss");
    var bossBonuses = new Dictionary<CombatKey, uint>();
    for (var index = 0; index < bossCount; index++)
    {
        var key = ReadKey(reader);
        var totalHp = reader.ReadInt32();
        var totalScore = reader.ReadInt32();
        var initiallyScheduled = reader.ReadBoolean();
        if (totalHp <= 0 || totalScore < 0)
            throw new InvalidDataException($"Invalid boss totals at record {index}: {path}");
        if (initiallyScheduled)
        {
            var profileKey = key.WithoutUid();
            bossBonuses[profileKey] = checked(bossBonuses.GetValueOrDefault(profileKey) + (uint)totalScore);
        }
    }

    var componentCount = ReadCount(reader, "boss component");
    for (var index = 0; index < componentCount; index++)
    {
        ReadKey(reader);
        reader.ReadByte();
        reader.ReadByte();
        reader.ReadInt32();
        ReadTemplate(reader);
    }

    var runtimeCount = ReadCount(reader, "runtime");
    var runtimeScores = new Dictionary<CombatTargetKey, uint>(runtimeCount);
    var hitMaximums = new Dictionary<CombatKey, uint>();
    for (var index = 0; index < runtimeCount; index++)
    {
        var profileKey = ReadKey(reader);
        var runtimeUid = profileKey.Uid;
        reader.ReadUInt16(); // Resource UID. The runtime UID is the HP wire selector.
        var template = ReadTemplate(reader);
        if (template.Score < 0)
            throw new InvalidDataException($"Negative runtime score at record {index}: {path}");
        var targetKey = new CombatTargetKey(profileKey.WithoutUid(), runtimeUid);
        if (!runtimeScores.TryAdd(targetKey, (uint)template.Score))
            throw new InvalidDataException($"Duplicate runtime score key at record {index}: {targetKey}");
        hitMaximums[profileKey.WithoutUid()] = checked(
            hitMaximums.GetValueOrDefault(profileKey.WithoutUid()) + (uint)template.Score);
    }

    if (stream.Position != stream.Length)
        throw new InvalidDataException($"DCC7 has {stream.Length - stream.Position} trailing bytes: {path}");
    return new CatalogData(runtimeScores, hitMaximums, bossBonuses);
}

static HpData ReadHpData(string path, IReadOnlyDictionary<CombatTargetKey, uint> runtimeScores)
{
    var profileRegex = new Regex(@"^\s*\{(?<v>[-0-9u,]+)\},\s*$", RegexOptions.Compiled);
    var targetScores = new List<uint>();
    var profiles = new List<HpProfile>();
    var matchedRuntimeKeys = new HashSet<CombatTargetKey>();
    var effectiveHitMaximums = new Dictionary<CombatKey, uint>();
    var section = string.Empty;

    foreach (var line in File.ReadLines(path))
    {
        if (line.StartsWith("static const struct hp_sync_profile_def", StringComparison.Ordinal))
        {
            section = "profiles";
            continue;
        }
        if (line.StartsWith("static const struct hp_sync_target_def", StringComparison.Ordinal))
        {
            section = "targets";
            continue;
        }
        if (section.Length == 0)
            continue;
        if (line.Trim() == "};")
        {
            // Current catalogs append newer maps in logical order, not row order.
            if (section == "profiles")
            {
                profiles.Sort((a, b) => a.FirstRow.CompareTo(b.FirstRow));
                uint end = 0;
                foreach (var range in profiles)
                {
                    if (range.FirstRow != end)
                        throw new InvalidDataException("HP profile ranges overlap or contain gaps.");
                    end = checked(end + range.TargetCount);
                }
            }
            section = string.Empty;
            continue;
        }
        var match = profileRegex.Match(line);
        if (!match.Success)
            continue;
        var values = match.Groups["v"].Value.Split(',')
            .Select(value => int.Parse(value.TrimEnd('u'), CultureInfo.InvariantCulture))
            .ToArray();
        if (section == "profiles")
        {
            if (values.Length != 11)
                throw new InvalidDataException($"Unexpected HP profile row: {line}");
            var key = new CombatKey(
                checked((byte)values[1]), checked((byte)values[0]), checked((byte)values[2]),
                checked((byte)values[3]), checked((byte)values[6]), 0);
            profiles.Add(new HpProfile(key, checked((uint)values[9]), checked((uint)values[10])));
            continue;
        }

        if (values.Length != 12)
            throw new InvalidDataException($"Unexpected HP target row: {line}");
        var rowIndex = checked((uint)targetScores.Count);
        var profile = FindProfile(profiles, rowIndex);
        var selector = checked((ushort)values[6]);
        var targetType = checked((byte)values[8]);
        var rewardKind = checked((byte)values[9]);
        var targetKey = new CombatTargetKey(profile.Key, selector);
        var score = runtimeScores.GetValueOrDefault(targetKey);
        if (runtimeScores.ContainsKey(targetKey))
            matchedRuntimeKeys.Add(targetKey);
        // Type4 preserves HP on hits; only HP-terminal targets contribute kill score.
        // Keep key coverage separate from eligibility, just as for random crates.
        if (targetType == 4 || rewardKind == 5)
            score = 0;
        targetScores.Add(score);
        effectiveHitMaximums[profile.Key] = checked(
            effectiveHitMaximums.GetValueOrDefault(profile.Key) + score);
    }

    if (profiles.Count == 0 || targetScores.Count == 0)
        throw new InvalidDataException($"No HP profiles/targets parsed: {path}");
    var expectedTargets = checked((int)(profiles[^1].FirstRow + profiles[^1].TargetCount));
    if (targetScores.Count != expectedTargets)
        throw new InvalidDataException($"HP target count mismatch: parsed={targetScores.Count} expected={expectedTargets}");
    return new HpData(targetScores, profiles, matchedRuntimeKeys, effectiveHitMaximums);
}

static HpProfile FindProfile(IReadOnlyList<HpProfile> profiles, uint rowIndex)
{
    var low = 0;
    var high = profiles.Count - 1;
    while (low <= high)
    {
        var middle = low + ((high - low) >> 1);
        var profile = profiles[middle];
        if (rowIndex < profile.FirstRow)
            high = middle - 1;
        else if (rowIndex >= profile.FirstRow + profile.TargetCount)
            low = middle + 1;
        else
            return profile;
    }
    throw new InvalidDataException($"HP target row {rowIndex} is not owned by a profile.");
}

static int ReadCount(BinaryReader reader, string name)
{
    var count = reader.ReadInt32();
    if (count is < 1 or > 1_000_000)
        throw new InvalidDataException($"Invalid {name} count: {count}");
    return count;
}

static CombatKey ReadKey(BinaryReader reader) => new(
    reader.ReadByte(), reader.ReadByte(), reader.ReadByte(), reader.ReadByte(), reader.ReadByte(), reader.ReadUInt16());

static CombatTemplate ReadTemplate(BinaryReader reader) => new(
    reader.ReadInt32(), reader.ReadByte(), reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32());

readonly record struct CombatKey(byte Hd, byte Episode, byte Dungeon, byte Stage, byte Slot, ushort Uid)
{
    public CombatKey WithoutUid() => this with { Uid = 0 };
}

readonly record struct CombatTargetKey(CombatKey Profile, ushort Uid);
readonly record struct CombatTemplate(int Resource, byte Category, int Hp, int Collision, int Score, int Defense);
readonly record struct HpProfile(CombatKey Key, uint FirstRow, uint TargetCount);
readonly record struct CatalogData(
    IReadOnlyDictionary<CombatTargetKey, uint> RuntimeScores,
    IReadOnlyDictionary<CombatKey, uint> HitMaximums,
    IReadOnlyDictionary<CombatKey, uint> BossBonuses);
readonly record struct HpData(
    IReadOnlyList<uint> TargetScores,
    IReadOnlyList<HpProfile> Profiles,
    IReadOnlySet<CombatTargetKey> MatchedRuntimeKeys,
    IReadOnlyDictionary<CombatKey, uint> EffectiveHitMaximums);
