"""Generate the exact KR cumulative curve. T[index] starts level index+1.
T[199] starts level 200; T[200] caps its final experience bar. Never use floating point.
The frozen v2 table is retained solely for explicit offline migration.
"""
from pathlib import Path
import csv
import sys
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'release/components/dungeon_progression'

def tables():
    with (DATA / 'character_experience.csv').open() as f:
        rows = list(csv.DictReader(f))
    assert [int(r['index']) for r in rows] == list(range(201))
    values = [int(r['total_experience']) for r in rows]
    assert values[0] == 0 and all(a < b for a, b in zip(values, values[1:]))
    assert (values[1], values[198], values[199], values[200]) == (4000,66463315200,67955751200,69469351200)
    assert max(b-a for a,b in zip(values,values[1:])) == 1513600000
    assert all(0 < b-a <= 2**31-1 for a,b in zip(values,values[1:]))
    with (DATA / 'character_experience_v2.csv').open() as f:
        old = list(csv.DictReader(f))
    assert [int(r['level']) for r in old] == list(range(100))
    legacy = [0,0]
    for row in old[1:]: legacy.append(legacy[-1] + int(row['experience_to_next']))
    return values, legacy

def outputs():
    values, legacy = tables()
    header = '// Generated by scripts/generate_character_experience.py; do not edit.\n'
    yield 'managed/Services/CharacterExperienceTable.g.cs', header + 'namespace OpenNanaimo.Adapter.Services;\n\ninternal static class CharacterExperienceTable\n{\n    internal static readonly long[] Thresholds =\n    [\n' + ''.join(f'        {v}L, // T[{i}]' + (' final level-200 bar cap' if i == 200 else '') + '\n' for i,v in enumerate(values)) + '    ];\n    internal static readonly long[] LegacyV2 =\n    [\n' + ''.join(f'        {v}L, // level {i}\n' for i,v in enumerate(legacy)) + '    ];\n}\n'
    yield 'release/components/dungeon_progression/character_experience_table.inc', header + 'static const unsigned long long progression_experience_thresholds[201] = {\n' + ''.join(f'    {v}ULL, /* T[{i}] */\n' for i,v in enumerate(values)) + '};\nstatic const unsigned long long progression_experience_v2[101] = {\n' + ''.join(f'    {v}ULL, /* level {i} */\n' for i,v in enumerate(legacy)) + '};\n'

if __name__ == '__main__':
    for name, content in outputs():
        path = ROOT / name
        if '--check' in sys.argv:
            assert path.read_text('utf8') == content, name
        else: path.write_text(content, encoding='utf8', newline='\n')
    print('KR curve v3: 201 exact integer rows; cap T[200]=69469351200; maximum level 200')
