"""Generate native AVATA HP/MP effects from the same encrypted resource as managed.

Requires PyCryptodome for the offline AES decode. No client binary or player state
is modified. HP/MP semantics: AVATA loader 94FCF0, consumers 94F330/94F460.
"""
from pathlib import Path
import argparse
import hashlib


def render(resource: Path) -> str:
    from Crypto.Cipher import AES
    encrypted = resource.read_bytes()
    raw = AES.new(bytes.fromhex('0123456789abcdef123456789abcdef0'), AES.MODE_CBC, bytes(16)).decrypt(encrypted)
    padding = raw[-1]
    if not 1 <= padding <= 16 or raw[-padding:] != bytes([padding]) * padding:
        raise ValueError('Invalid resource padding')
    fields = raw[:-padding].decode('gbk').split('#')
    if fields[0] != 'AVATA':
        raise ValueError('Not an AVATA resource')
    rows = []
    codes = set()
    for n in range(int(fields[2])):
        r = fields[3 + 25*n:3 + 25*(n+1)]
        if len(r) != 25: raise ValueError('Truncated AVATA row')
        code = int(r[4])
        if code in codes: raise ValueError('Duplicate AVATA code')
        codes.add(code)
        flat, percent = [0, 0], [0, 0]
        for i in (13, 16, 19):
            kind, mode, value = map(int, r[i:i+3])
            if kind not in (1, 2): continue
            if value < 0: raise ValueError('Negative resource effect')
            if mode:
                flat[kind-1], percent[kind-1] = 0, value
            else:
                flat[kind-1] += value
        if any(flat + percent):
            rows.append((code, flat[0], percent[0], flat[1], percent[1]))
    lines = [
        '/* Generated by scripts/generate_avatar_resource_effects.py; do not edit.',
        f'   ava._D1 SHA256 {hashlib.sha256(encrypted).hexdigest().upper()} */',
        '#ifndef NANAIMO_AVATAR_RESOURCE_DATA_INC',
        '#define NANAIMO_AVATAR_RESOURCE_DATA_INC',
        'struct avatar_resource_row { unsigned code,hp_flat,hp_percent,mp_flat,mp_percent; };',
        'static const struct avatar_resource_row g_avatar_resource_rows[] = {'
    ]
    lines += ['    {' + ','.join(str(v)+'u' for v in row) + '},' for row in sorted(rows)]
    lines += ['};', '#endif', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('resource', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'release/components/inventory_instances/avatar_resource_data.inc')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render(args.resource)
    if args.check:
        if args.output.read_text(encoding='utf8') != text: raise SystemExit('AVATA generated data differs')
    else:
        args.output.write_text(text, encoding='utf8', newline='\n')
    print('AVATAR_RESOURCE_DATA_PASS')


if __name__ == '__main__': main()
