"""Generate matching cumulative EXP thresholds from the user-owned single-level table."""
from pathlib import Path
import csv, sys
ROOT = Path(__file__).resolve().parents[1]

def outputs():
    rows = list(csv.DictReader((ROOT / 'release/components/dungeon_progression/character_experience.csv').open()))
    assert [int(r['level']) for r in rows] == list(range(100))
    costs = [int(r['experience_to_next']) for r in rows]
    assert costs[0] == 0 and all(x > 0 for x in costs[1:])
    thresholds = [0, 0]
    for cost in costs[1:]: thresholds.append(thresholds[-1] + cost)
    assert thresholds[-1] < 2**32
    header = '// Generated by scripts/generate_character_experience.py; do not edit.\n'
    yield 'managed/Services/CharacterExperienceTable.g.cs', header + 'namespace OpenNanaimo.Adapter.Services;\n\ninternal static class CharacterExperienceTable\n{\n    internal static readonly uint[] Thresholds =\n    [\n' + ''.join(f'        {v}u, // level {i}' + (' display cap only' if i == 100 else '') + '\n' for i,v in enumerate(thresholds)) + '    ];\n}\n'
    yield 'release/components/dungeon_progression/character_experience_table.inc', header + 'static const unsigned progression_experience_thresholds[101] = {\n' + ''.join(f'    {v}u, /* {i} */\n' for i,v in enumerate(thresholds)) + '};\n'

if __name__ == '__main__':
    for name, content in outputs():
        path = ROOT / name
        if '--check' in sys.argv:
            assert path.read_text('utf8') == content, name
        else: path.write_text(content, encoding='utf8', newline='\n')
    print('character experience thresholds: consistent; maximum level 99')
