# Inventory administration UI for the Korean Nanaimo launcher.
# Dot-source this file, then call Initialize-InventoryAdmin and Save-InventoryAdminState.

function Invoke-InventoryAdminPython([string[]]$Arguments) {
    $root=Split-Path $PSScriptRoot -Parent
    $bundled=Join-Path $root 'tools\python\python.exe'
    $py=if(Test-Path -LiteralPath $bundled){$bundled}else{(Get-Command python -ErrorAction Stop).Source}
    # Windows PowerShell 5.1 turns redirected stderr into NativeCommandError.
    # Capture the entire child result before applying the caller's Stop policy.
    $savedPreference=$ErrorActionPreference
    try{
        $ErrorActionPreference='Continue'
        $output=@(& $py -B @Arguments 2>&1)
        $exitCode=$LASTEXITCODE
    }finally{$ErrorActionPreference=$savedPreference}
    $text=($output|ForEach-Object{$_.ToString()})-join"`r`n"
    if($exitCode-ne0){throw "Inventory backend failed (exit=$exitCode):`r`n$text"}
    return $text.Trim()
}
function Remove-InventoryAdminKnownCards($Cards,$KnownCards){
    foreach($row in @($Cards)){if($KnownCards.ContainsKey([uint32]$row.code)){[void]$Cards.Remove($row)}}
}
function New-InventoryAdminGrid($parent,[int]$x,[int]$y,[int]$w,[int]$h){
    $g=New-Object Windows.Forms.DataGridView;$g.Location=New-Object Drawing.Point($x,$y);$g.Size=New-Object Drawing.Size($w,$h);$g.ReadOnly=$true;$g.AllowUserToAddRows=$false;$g.AllowUserToDeleteRows=$false;$g.MultiSelect=$false;$g.SelectionMode='FullRowSelect';$g.AutoSizeColumnsMode='DisplayedCells';$g.RowHeadersVisible=$false;$parent.Controls.Add($g);return $g
}
function New-InventoryAdminTable([string[]]$Columns){$t=New-Object Data.DataTable;$t.TableName='T'+[guid]::NewGuid().ToString('N');foreach($c in $Columns){[void]$t.Columns.Add($c)};return ,$t}
function Escape-InventoryAdminFilter([string]$s){return $s.Replace("'","''").Replace('[','[[]').Replace('%','[%]').Replace('*','[*]')}
function Set-InventoryAdminFilter($view,[string]$q,[string[]]$columns){$q=Escape-InventoryAdminFilter $q.Trim();if(-not$q){$view.RowFilter='';return};$view.RowFilter=(($columns|ForEach-Object{"[$_] LIKE '%$q%'"})-join' OR ')}
function Get-InventoryAdminCode($grid){if(-not$grid.CurrentRow){return 0};try{return [uint32]$grid.CurrentRow.Cells['ID'].Value}catch{return 0}}
function Write-InventoryAdminTempJson($value){$p=Join-Path ([IO.Path]::GetTempPath()) ('nanaimo-inventory-'+[guid]::NewGuid().ToString('N')+'.json');[IO.File]::WriteAllText($p,($value|ConvertTo-Json -Depth 8 -Compress),(New-Object Text.UTF8Encoding($false)));return $p}

function Get-InventoryAdminProfiles($Root,$Backend,$DefaultNameHex){$arguments=@($Backend,'profiles','--root',$Root);if($DefaultNameHex){$arguments+=@('--name-hex',$DefaultNameHex)};$profiles=Invoke-InventoryAdminPython $arguments|ConvertFrom-Json;foreach($profile in $profiles){$profile}}
function Read-InventoryAdminSnapshot($Root,$Backend,$Profile){$tmp=Join-Path ([IO.Path]::GetTempPath()) ('nanaimo-snapshot-'+[guid]::NewGuid().ToString('N')+'.json');$args=@($Backend,'snapshot','--root',$Root,'--name-hex',[string]$Profile.name_hex,'--output',$tmp);if($null-ne$Profile.character_id-and[string]$Profile.character_id){$args+=@('--character-id',[string]$Profile.character_id)};try{[void](Invoke-InventoryAdminPython $args);return (Get-Content -LiteralPath $tmp -Raw -Encoding UTF8|ConvertFrom-Json)}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}}

function Import-InventoryAdminSnapshot($Context,$Snap,$Profile){foreach($list in @($Context.Clothing,$Context.Pets,$Context.GameItems,$Context.Furniture,$Context.Cards)){$list.Clear()};foreach($x in $Snap.clothing){[void]$Context.Clothing.Add([uint32]$x)};foreach($x in $Snap.pets){[void]$Context.Pets.Add([pscustomobject]@{code=[uint32]$x.code;upgrade_material=[uint32]$x.upgrade_material;gems=@([uint32]$x.gems[0],[uint32]$x.gems[1],[uint32]$x.gems[2])})};foreach($x in $Snap.game_items){[void]$Context.GameItems.Add([pscustomobject]@{code=[uint32]$x.code;count=[uint32]$x.count;carrier=[string]$x.carrier})};foreach($x in $Snap.furniture){[void]$Context.Furniture.Add([pscustomobject]@{code=[uint32]$x.code;index=[uint16]$x.index;placed=[bool]$x.placed;type=[byte]$x.type;x=[int16]$x.x;y=[int16]$x.y;z=[byte]$x.z;mirror=[byte]$x.mirror})};foreach($x in $Snap.cards){[void]$Context.Cards.Add([pscustomobject]@{code=[uint32]$x.code;count=[uint32]$x.count})};$Context.NameHex=[string]$Snap.name_hex;if(-not$Context.NameHex){$Context.NameHex=[string]$Profile.name_hex};$Context.CharacterId=if($null-ne$Snap.character_id){[long]$Snap.character_id}elseif($null-ne$Profile.character_id-and[string]$Profile.character_id){[long]$Profile.character_id}else{$null};$Context.SelectedProfile=$Profile;$Context.AccountSuffix=[string]$Snap.account_suffix;$Context.Shop=$Snap.shop;$Context.Profile=if($Snap.profile){$Snap.profile}else{[pscustomobject]@{character_name=[string]$Profile.character_name;gender=$Profile.gender;level=$Profile.level;hp_max=$(if($null-ne$Profile.hp_max){$Profile.hp_max}else{1500});mp_max=$(if($null-ne$Profile.mp_max){$Profile.mp_max}else{100});coin=[uint64]$Snap.shop.coin;nana_point=[uint64]$Snap.shop.nana;attack=$(if($null-ne$Profile.attack){$Profile.attack}else{0});defense=$(if($null-ne$Profile.defense){$Profile.defense}else{0})}}}
function Set-InventoryAdminProfile($Context,$Profile){if($null-eq$Profile){return};if($Context.SelectedProfile-and[string]$Context.NameHex-ieq[string]$Profile.name_hex-and[string]$Context.CharacterId-eq[string]$Profile.character_id){return};Import-InventoryAdminSnapshot $Context (Read-InventoryAdminSnapshot $Context.Root $Context.Backend $Profile) $Profile;if($Context.RefreshAll){&$Context.RefreshAll};$Context.ProfileSelectorSync=$true;try{foreach($selector in $Context.ProfileSelectors){for($i=0;$i-lt$selector.Items.Count;$i++){if([string]$selector.Items[$i].name_hex-eq$Context.NameHex-and[string]$selector.Items[$i].character_id-eq[string]$Context.CharacterId){$selector.SelectedIndex=$i;break}}}}finally{$Context.ProfileSelectorSync=$false};if($Context.ProfileChanged){&$Context.ProfileChanged $Context}}
function Add-InventoryAdminProfileSelector($Parent,$Context){$label=New-Object Windows.Forms.Label;$label.Text='用户档案';$label.Location='910,0';$label.Size='165,14';$label.ForeColor=[Drawing.Color]::DarkGreen;$Parent.Controls.Add($label);$combo=New-Object Windows.Forms.ComboBox;$combo.Location='910,16';$combo.Size='165,28';$combo.DropDownStyle='DropDownList';$combo.DropDownWidth=360;$combo.DisplayMember='display';foreach($profile in $Context.Profiles){[void]$combo.Items.Add($profile)};$Parent.Controls.Add($combo);[void]$Context.ProfileSelectors.Add($combo);$combo.add_SelectedIndexChanged(({if(-not$Context.ProfileSelectorSync-and$combo.SelectedIndex-ge0){Set-InventoryAdminProfile $Context $combo.SelectedItem}}).GetNewClosure());for($i=0;$i-lt$combo.Items.Count;$i++){if([string]$combo.Items[$i].name_hex-eq$Context.NameHex-and[string]$combo.Items[$i].character_id-eq[string]$Context.CharacterId){$combo.SelectedIndex=$i;break}}}
function ConvertTo-InventoryAdminNameHex([string]$Name){
    $Name=$Name.Trim();$encoding=[Text.Encoding]::GetEncoding(936,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback));$bytes=$encoding.GetBytes($Name)
    if($bytes.Length-lt1-or$bytes.Length-gt14-or(@($Name.ToCharArray()|Where-Object{[char]::IsControl($_)}).Count-gt0)){throw '用户名/角色显示名必须是1到14个GBK字节且不能包含控制字符。'}
    return (($bytes|ForEach-Object{$_.ToString('X2')})-join '')
}
function Find-InventoryAdminProfile($Context,[string]$Identity){
    $needle=$Identity.Trim();if(-not$needle){return $null};$hex='';try{$hex=ConvertTo-InventoryAdminNameHex $needle}catch{}
    # Account identity wins over a different character with the same display name.
    $account=@($Context.Profiles|Where-Object{[string]$_.username -ieq $needle})
    if($account.Count){return $account[0]}
    return @($Context.Profiles|Where-Object{
        ([string]$_.character_name -ieq $needle) -or ([string]$_.display -ieq $needle) -or ($hex -and [string]$_.name_hex -ieq $hex)
    })[0]
}
function Add-InventoryAdminProfileToSelectors($Context,$Profile){
    $Context.Profiles=@($Context.Profiles+$Profile);$Context.ProfileSelectorSync=$true
    try{foreach($selector in $Context.ProfileSelectors){$exists=$false;foreach($item in $selector.Items){if([string]$item.name_hex-ieq[string]$Profile.name_hex-and[string]$item.character_id-eq[string]$Profile.character_id){$exists=$true;break}};if(-not$exists){[void]$selector.Items.Add($Profile)}}}finally{$Context.ProfileSelectorSync=$false}
}
function Ensure-InventoryAdminProfile($Context,[string]$Identity){
    $needle=$Identity.Trim();if(-not$needle){throw '用户名/角色显示名不能为空。'}
    $existing=Find-InventoryAdminProfile $Context $needle
    if($existing-and$null-ne$existing.account_id-and$null-eq$existing.character_id){throw 'Selected account has no character yet.'}
    if($existing){
        Set-InventoryAdminProfile $Context $existing
        if($null-eq$Context.CharacterId){
            $path=Join-Path $Context.Root ('inventory_admin_profiles/'+$Context.NameHex+'.json')
            if(-not(Test-Path -LiteralPath $path)){
                [void](Save-InventoryAdminState $Context $Context.NameHex $Context.Shop $Context.Profile -Clone)
            }
        }
        return $Context.SelectedProfile
    }
    $targetHex=ConvertTo-InventoryAdminNameHex $needle
    if(-not$Context.SelectedProfile){throw '没有可复制的当前用户档案。'}
    $shop=$Context.Shop;if(-not$shop){$shop=[pscustomobject]@{coin=0;nana=0;equipped=@(0,0,0,0,0);effect=0;selected_pet=0}}
    $profile=$Context.Profile;if(-not$profile){$profile=[pscustomobject]@{hp_max=1500;mp_max=100;coin=[uint64]$shop.coin;nana_point=[uint64]$shop.nana;attack=0;defense=0}}
    [void](Save-InventoryAdminState $Context $targetHex $shop $profile -Clone)
    $new=[pscustomobject]@{account_id=$null;username=$needle;account_online=$false;character_id=$null;character_name=$needle;character_online=$false;gender=$profile.gender;level=$profile.level;hp_max=$profile.hp_max;mp_max=$profile.mp_max;attack=$profile.attack;defense=$profile.defense;coin=$shop.coin;nana=$shop.nana;name_hex=$targetHex;display=$needle;source='sidecar'}
    Add-InventoryAdminProfileToSelectors $Context $new
    Set-InventoryAdminProfile $Context $new
    return $Context.SelectedProfile
}

function Initialize-InventoryAdmin($Tabs,[string]$Root,[string]$NameHex){
    $backend=Join-Path $Root 'gui_launcher\inventory_admin_backend.py';if(-not(Test-Path -LiteralPath $backend)){throw '物品管理后端不存在。'}
    $dataDir=Join-Path $Root 'gui_launcher\data';$needed='inventory_clothing.json','inventory_pets.json','inventory_pet_gems.json','inventory_game_items.json','inventory_furniture.json','inventory_cards.json';foreach($n in $needed){if(-not(Test-Path -LiteralPath (Join-Path $dataDir $n))){throw "物品目录缺失: $n"}}
    $profiles=@(Get-InventoryAdminProfiles $Root $backend $NameHex);if(-not$profiles.Count){throw '没有可管理的用户档案。'}
    $initial=@($profiles|Where-Object{[string]$_.name_hex-eq$NameHex})[0];if(-not$initial){$initial=$profiles[0]}
    $snap=Read-InventoryAdminSnapshot $Root $backend $initial
    $catalog=@{clothing=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_clothing.json') -Raw -Encoding UTF8|ConvertFrom-Json;pets=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_pets.json') -Raw -Encoding UTF8|ConvertFrom-Json;gems=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_pet_gems.json') -Raw -Encoding UTF8|ConvertFrom-Json;game=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_game_items.json') -Raw -Encoding UTF8|ConvertFrom-Json;furniture=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_furniture.json') -Raw -Encoding UTF8|ConvertFrom-Json;cards=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_cards.json') -Raw -Encoding UTF8|ConvertFrom-Json}
    $ctx=[pscustomobject]@{Root=$Root;Backend=$backend;AccountSuffix='';NameHex='';CharacterId=$null;SelectedProfile=$null;Profiles=@($profiles);ProfileSelectors=New-Object Collections.ArrayList;ProfileSelectorSync=$false;ProfileChanged=$null;Profile=$null;Catalog=$catalog;Clothing=New-Object Collections.ArrayList;Pets=New-Object Collections.ArrayList;GameItems=New-Object Collections.ArrayList;Furniture=New-Object Collections.ArrayList;Cards=New-Object Collections.ArrayList;CardAddAllButton=$null;CardRemoveAllButton=$null;Shop=$null;RefreshAll=$null}
    Import-InventoryAdminSnapshot $ctx $snap $initial
    $byCloth=@{};foreach($x in $catalog.clothing){$byCloth[[uint32]$x.id]=$x};$byPet=@{};foreach($x in $catalog.pets){$byPet[[uint32]$x.id]=$x};$byGem=@{};foreach($x in $catalog.gems){$byGem[[uint32]$x.id]=$x};$byGame=@{};foreach($x in $catalog.game){$byGame[[uint32]$x.id]=$x};$byFurniture=@{};foreach($x in $catalog.furniture){$byFurniture[[uint32]$x.id]=$x};$byCard=@{};foreach($x in $catalog.cards){$byCard[[uint32]$x.id]=$x}
    # Clothing box
    $tab=New-Object Windows.Forms.TabPage;$tab.Text='衣物箱管理';$Tabs.TabPages.Add($tab);$ownedSearch=New-Object Windows.Forms.TextBox;$ownedSearch.Location='15,15';$ownedSearch.Size='350,26';$tab.Controls.Add($ownedSearch);$allSearch=New-Object Windows.Forms.TextBox;$allSearch.Location='555,15';$allSearch.Size='350,26';$tab.Controls.Add($allSearch)
    $ownedGrid=New-InventoryAdminGrid $tab 15 50 430 650;$allGrid=New-InventoryAdminGrid $tab 555 50 525 650
    $ot=New-InventoryAdminTable @('名称','ID','部位','性别');$ov=New-Object Data.DataView;$ov.Table=$ot;$ownedGrid.DataSource=$ov;$at=New-InventoryAdminTable @('名称','ID','部位','性别','效果说明');foreach($x in $catalog.clothing){[void]$at.Rows.Add($x.name,[string]$x.id,$x.part,$x.gender,$x.effect_description)};$av=New-Object Data.DataView;$av.Table=$at;$allGrid.DataSource=$av
    $refreshClothing={ $ot.Rows.Clear();foreach($code in $ctx.Clothing){$x=$byCloth[[uint32]$code];if($x){[void]$ot.Rows.Add($x.name,[string]$x.id,$x.part,$x.gender)}} }.GetNewClosure();&$refreshClothing
    $add=New-Object Windows.Forms.Button;$add.Text='← 添加';$add.Location='460,260';$add.Size='80,35';$tab.Controls.Add($add);$del=New-Object Windows.Forms.Button;$del.Text='删除 →';$del.Location='460,310';$del.Size='80,35';$tab.Controls.Add($del)
    $ownedSearch.add_TextChanged(({Set-InventoryAdminFilter $ov $ownedSearch.Text @('名称','ID','部位','性别')}).GetNewClosure());$allSearch.add_TextChanged(({Set-InventoryAdminFilter $av $allSearch.Text @('名称','ID','部位','性别','效果说明')}).GetNewClosure())
    $add.add_Click(({ $c=Get-InventoryAdminCode $allGrid;if($c-and-not($ctx.Clothing-contains$c)){if($ctx.Clothing.Count-ge256){[Windows.Forms.MessageBox]::Show('衣物箱上限为256种。')|Out-Null;return};[void]$ctx.Clothing.Add($c);&$refreshClothing}}).GetNewClosure());$del.add_Click(({ $c=Get-InventoryAdminCode $ownedGrid;if($c){[void]$ctx.Clothing.Remove($c);&$refreshClothing}}).GetNewClosure());$allGrid.add_CellDoubleClick(({param($s,$e)$add.PerformClick()}).GetNewClosure())

    # Pet box + gems/attributes
    $petTab=New-Object Windows.Forms.TabPage;$petTab.Text='宠物箱管理';$Tabs.TabPages.Add($petTab)
    # Reserve the top row for the shared profile selector; keep the grid bottom aligned with the other admin controls.
    $petContentTop=51;$petSearchTop=75;$petGridTop=107;$petGridHeight=418
    $ph1=New-Object Windows.Forms.Label;$ph1.Text='① 已有宠物：先选中要查看或编辑的宠物';$ph1.Location=New-Object Drawing.Point(10,$petContentTop);$ph1.Size='340,22';$ph1.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph1)
    $ph2=New-Object Windows.Forms.Label;$ph2.Text='② 全量宠物：筛选后加入左侧宠物箱';$ph2.Location=New-Object Drawing.Point(375,$petContentTop);$ph2.Size='340,22';$ph2.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph2)
    $ph3=New-Object Windows.Forms.Label;$ph3.Text='③ 全量宝石：选中后装入左侧宠物';$ph3.Location=New-Object Drawing.Point(740,$petContentTop);$ph3.Size='340,22';$ph3.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph3)
    $ps1=New-Object Windows.Forms.TextBox;$ps1.Location=New-Object Drawing.Point(10,$petSearchTop);$ps1.Size='280,25';$petTab.Controls.Add($ps1);$ps2=New-Object Windows.Forms.TextBox;$ps2.Location=New-Object Drawing.Point(375,$petSearchTop);$ps2.Size='280,25';$petTab.Controls.Add($ps2);$gs=New-Object Windows.Forms.TextBox;$gs.Location=New-Object Drawing.Point(740,$petSearchTop);$gs.Size='280,25';$petTab.Controls.Add($gs)
    $pg1=New-InventoryAdminGrid $petTab 10 $petGridTop 340 $petGridHeight;$pg2=New-InventoryAdminGrid $petTab 375 $petGridTop 340 $petGridHeight;$gg=New-InventoryAdminGrid $petTab 740 $petGridTop 340 $petGridHeight
    $pt1=New-InventoryAdminTable @('名称','ID','基础攻击','有效攻击','HP加成','MP加成','槽位','宝石1','宝石2','宝石3');$pv1=New-Object Data.DataView;$pv1.Table=$pt1;$pg1.DataSource=$pv1;$pt2=New-InventoryAdminTable @('名称','ID','基础攻击','槽位','等级需求');foreach($x in $catalog.pets){[void]$pt2.Rows.Add($x.name,[string]$x.id,[string]$x.base_attack,[string]$x.slot_count,[string]$x.level_requirement)};$pv2=New-Object Data.DataView;$pv2.Table=$pt2;$pg2.DataSource=$pv2;$gt=New-InventoryAdminTable @('名称','ID','效果','攻击','攻击%','HP','MP');foreach($x in $catalog.gems){[void]$gt.Rows.Add($x.name,[string]$x.id,$x.effect,[string]$x.attack_flat,[string]$x.attack_percent,[string]$x.hp,[string]$x.mp)};$gv=New-Object Data.DataView;$gv.Table=$gt;$gg.DataSource=$gv
    $petDetail=New-Object Windows.Forms.Label;$petDetail.Location='15,615';$petDetail.Size='1040,45';$petDetail.Font=New-Object Drawing.Font('Microsoft YaHei UI',10);$petTab.Controls.Add($petDetail)
    $refreshPets={ $selected=Get-InventoryAdminCode $pg1;$pt1.Rows.Clear();foreach($r in $ctx.Pets){$p=$byPet[[uint32]$r.code];if(-not$p){continue};$flat=0;$pct=0;$hp=0;$mp=0;$names=@();foreach($g in $r.gems){$d=$byGem[[uint32]$g];if($d){$flat+=[int]$d.attack_flat;$pct+=[int]$d.attack_percent;$hp+=[int]$d.hp;$mp+=[int]$d.mp;$names+=$d.name}else{$names+='-'}};$base=[int]$p.base_attack;$eff=$base+$flat+[math]::Floor($base*$pct/100);[void]$pt1.Rows.Add($p.name,[string]$p.id,[string]$base,[string]$eff,[string]$hp,[string]$mp,[string]$p.slot_count,$names[0],$names[1],$names[2])};if($selected){foreach($row in $pg1.Rows){if([uint32]$row.Cells['ID'].Value-eq$selected){$row.Selected=$true;$pg1.CurrentCell=$row.Cells[0];break}}} }.GetNewClosure();&$refreshPets
    $petAdd=New-Object Windows.Forms.Button;$petAdd.Text='将中列宠物加入左列';$petAdd.Location='375,535';$petAdd.Size='200,34';$petTab.Controls.Add($petAdd);$petDel=New-Object Windows.Forms.Button;$petDel.Text='删除左列选中宠物';$petDel.Location='15,535';$petDel.Size='210,34';$petDel.BackColor=[Drawing.Color]::MistyRose;$petTab.Controls.Add($petDel);$upgrade=New-Object Windows.Forms.CheckBox;$upgrade.Text='黄金粉升级';$upgrade.Location='15,578';$upgrade.Size='130,28';$petTab.Controls.Add($upgrade)
    $slotButtons=@();for($i=0;$i-lt3;$i++){$b=New-Object Windows.Forms.Button;$b.Text="装入槽$($i+1)";$b.Location=New-Object Drawing.Point((740+$i*110),535);$b.Size='103,34';$petTab.Controls.Add($b);$slotButtons+=$b};$clearGem=New-Object Windows.Forms.Button;$clearGem.Text='清空指定槽';$clearGem.Location='740,575';$clearGem.Size='110,32';$petTab.Controls.Add($clearGem);$slotPick=New-Object Windows.Forms.NumericUpDown;$slotPick.Minimum=1;$slotPick.Maximum=3;$slotPick.Value=1;$slotPick.Location='860,578';$slotPick.Size='55,28';$petTab.Controls.Add($slotPick);$slotHint=New-Object Windows.Forms.Label;$slotHint.Text='槽号';$slotHint.Location='920,581';$slotHint.Size='45,25';$petTab.Controls.Add($slotHint);$petHelp=New-Object Windows.Forms.Label;$petHelp.Text='删除：左列选宠物 → 点左列下方红色按钮。装宝石：左列选宠物 → 右列选宝石 → 点装入槽1/2/3。';$petHelp.Location='15,665';$petHelp.Size='1040,30';$petHelp.ForeColor=[Drawing.Color]::DarkBlue;$petTab.Controls.Add($petHelp)
    $getPetRow={param([uint32]$code)return @($ctx.Pets|Where-Object{[uint32]$_.code-eq$code})[0]}.GetNewClosure()
    $updatePetDetail={ $c=Get-InventoryAdminCode $pg1;if(-not$c){$petDetail.Text='请选择已有宠物以查看属性和编辑宝石。';return};$r=&$getPetRow $c;$p=$byPet[$c];$upgrade.Checked=([uint32]$r.upgrade_material-ne0);$petDetail.Text="$($p.name) [$c]  基础攻击=$($p.base_attack)，槽位=$($p.slot_count)，年龄元数据=$($p.display_age)/$($p.max_age)，等级需求=$($p.level_requirement)，升级材料=$($p.upgrade_material)" }.GetNewClosure();$pg1.add_SelectionChanged($updatePetDetail);&$updatePetDetail
    $ps1.add_TextChanged(({Set-InventoryAdminFilter $pv1 $ps1.Text @('名称','ID','宝石1','宝石2','宝石3')}).GetNewClosure());$ps2.add_TextChanged(({Set-InventoryAdminFilter $pv2 $ps2.Text @('名称','ID','基础攻击','等级需求')}).GetNewClosure());$gs.add_TextChanged(({Set-InventoryAdminFilter $gv $gs.Text @('名称','ID','效果','攻击','攻击%','HP','MP')}).GetNewClosure())
    $petAdd.add_Click(({ $c=Get-InventoryAdminCode $pg2;if(-not$c-or@($ctx.Pets|Where-Object{$_.code-eq$c}).Count){return};if($ctx.Pets.Count-ge128){[Windows.Forms.MessageBox]::Show('宠物箱上限为128只；客户端当前一次最多展示56行，选中宠物会被保留在可见行。')|Out-Null;return};[void]$ctx.Pets.Add([pscustomobject]@{code=$c;upgrade_material=0;gems=@(0,0,0)});&$refreshPets}).GetNewClosure());$petDel.add_Click(({ $c=Get-InventoryAdminCode $pg1;if($c){$r=&$getPetRow $c;if($r){[void]$ctx.Pets.Remove($r);&$refreshPets}}}).GetNewClosure())
    for($i=0;$i-lt3;$i++){$slot=$i;$slotButtons[$i].add_Click(({ $pc=Get-InventoryAdminCode $pg1;$gc=Get-InventoryAdminCode $gg;if(-not$pc-or-not$gc){return};$r=&$getPetRow $pc;$p=$byPet[$pc];if($slot-ge[int]$p.slot_count){[Windows.Forms.MessageBox]::Show("该宠物只有 $($p.slot_count) 个宝石槽。")|Out-Null;return};$r.gems[$slot]=$gc;&$refreshPets;&$updatePetDetail}).GetNewClosure())}
    $clearGem.add_Click(({ $pc=Get-InventoryAdminCode $pg1;if(-not$pc){return};$r=&$getPetRow $pc;$r.gems[[int]$slotPick.Value-1]=0;&$refreshPets;&$updatePetDetail}).GetNewClosure());$upgrade.add_CheckedChanged(({ $pc=Get-InventoryAdminCode $pg1;if(-not$pc){return};$r=&$getPetRow $pc;$p=$byPet[$pc];$r.upgrade_material=if($upgrade.Checked){[uint32]$p.upgrade_material}else{0}}).GetNewClosure())

    # Game items
    $gameTab=New-Object Windows.Forms.TabPage;$gameTab.Text='游戏道具管理';$Tabs.TabPages.Add($gameTab);$gos=New-Object Windows.Forms.TextBox;$gos.Location='15,15';$gos.Size='350,26';$gameTab.Controls.Add($gos);$gas=New-Object Windows.Forms.TextBox;$gas.Location='555,15';$gas.Size='350,26';$gameTab.Controls.Add($gas);$gog=New-InventoryAdminGrid $gameTab 15 50 430 650;$gag=New-InventoryAdminGrid $gameTab 555 50 525 650
    $got=New-InventoryAdminTable @('名称','ID','数量','载体','分类');$gov=New-Object Data.DataView;$gov.Table=$got;$gog.DataSource=$gov;$gat=New-InventoryAdminTable @('名称','ID','载体','分类','说明','效果');foreach($x in $catalog.game){[void]$gat.Rows.Add($x.name,[string]$x.id,$x.carrier,$x.category,$x.description,$x.effect)};$gav=New-Object Data.DataView;$gav.Table=$gat;$gag.DataSource=$gav
    $refreshGame={ $got.Rows.Clear();foreach($r in $ctx.GameItems){$x=$byGame[[uint32]$r.code];[void]$got.Rows.Add($(if($x){$x.name}else{"ITEM-$($r.code)"}),[string]$r.code,[string]$r.count,$r.carrier,$(if($x){$x.category}else{''}))} }.GetNewClosure();&$refreshGame
    $qty=New-Object Windows.Forms.NumericUpDown;$qty.Minimum=1;$qty.Maximum=255;$qty.Value=1;$qty.Location='465,235';$qty.Size='75,28';$gameTab.Controls.Add($qty);$ga=New-Object Windows.Forms.Button;$ga.Text='← 增加';$ga.Location='460,275';$ga.Size='80,34';$gameTab.Controls.Add($ga);$gd=New-Object Windows.Forms.Button;$gd.Text='减少/删除 →';$gd.Location='450,325';$gd.Size='95,34';$gameTab.Controls.Add($gd)
    $gos.add_TextChanged(({Set-InventoryAdminFilter $gov $gos.Text @('名称','ID','载体','分类')}).GetNewClosure());$gas.add_TextChanged(({Set-InventoryAdminFilter $gav $gas.Text @('名称','ID','载体','分类','说明','效果')}).GetNewClosure())
    $ga.add_Click(({ $c=Get-InventoryAdminCode $gag;if(-not$c){return};$carrier=[string]$gag.CurrentRow.Cells['载体'].Value;$r=@($ctx.GameItems|Where-Object{$_.code-eq$c-and$_.carrier-eq$carrier})[0];if($r){$r.count=[math]::Min(255,[int]$r.count+[int]$qty.Value)}else{[void]$ctx.GameItems.Add([pscustomobject]@{code=$c;count=[uint32]$qty.Value;carrier=$carrier})};&$refreshGame}).GetNewClosure());$gd.add_Click(({ $c=Get-InventoryAdminCode $gog;if(-not$c){return};$carrier=[string]$gog.CurrentRow.Cells['载体'].Value;$r=@($ctx.GameItems|Where-Object{$_.code-eq$c-and$_.carrier-eq$carrier})[0];if($r){$r.count=[int]$r.count-[int]$qty.Value;if($r.count-le0){[void]$ctx.GameItems.Remove($r)};&$refreshGame}}).GetNewClosure())

    # Furniture
    $fTab=New-Object Windows.Forms.TabPage;$fTab.Text='装饰家具管理';$Tabs.TabPages.Add($fTab);$fos=New-Object Windows.Forms.TextBox;$fos.Location='15,15';$fos.Size='350,26';$fTab.Controls.Add($fos);$fas=New-Object Windows.Forms.TextBox;$fas.Location='555,15';$fas.Size='350,26';$fTab.Controls.Add($fas);$fog=New-InventoryAdminGrid $fTab 15 50 430 650;$fag=New-InventoryAdminGrid $fTab 555 50 525 650
    $fot=New-InventoryAdminTable @('名称','ID','实例','类型','已摆放','X','Y');$fov=New-Object Data.DataView;$fov.Table=$fot;$fog.DataSource=$fov;$fat=New-InventoryAdminTable @('名称','ID','类型','期限','金币','NANA','说明');foreach($x in $catalog.furniture){[void]$fat.Rows.Add($x.name,[string]$x.id,$x.type_name,[string]$x.days,[string]$x.coin,[string]$x.nana,$x.description)};$fav=New-Object Data.DataView;$fav.Table=$fat;$fag.DataSource=$fav
    $refreshFurniture={ $fot.Rows.Clear();foreach($r in $ctx.Furniture){$x=$byFurniture[[uint32]$r.code];[void]$fot.Rows.Add($(if($x){$x.name}else{"FURNITURE-$($r.code)"}),[string]$r.code,[string]$r.index,$(if($x){$x.type_name}else{$r.type}),$(if($r.placed){'是'}else{'否'}),[string]$r.x,[string]$r.y)} }.GetNewClosure();&$refreshFurniture
    $fa=New-Object Windows.Forms.Button;$fa.Text='← 添加实例';$fa.Location='450,275';$fa.Size='95,35';$fTab.Controls.Add($fa);$fd=New-Object Windows.Forms.Button;$fd.Text='删除实例 →';$fd.Location='450,325';$fd.Size='95,35';$fTab.Controls.Add($fd);$fos.add_TextChanged(({Set-InventoryAdminFilter $fov $fos.Text @('名称','ID','实例','类型','已摆放')}).GetNewClosure());$fas.add_TextChanged(({Set-InventoryAdminFilter $fav $fas.Text @('名称','ID','类型','说明')}).GetNewClosure())
    $fa.add_Click(({ $c=Get-InventoryAdminCode $fag;if(-not$c){return};if($ctx.Furniture.Count-ge254){[Windows.Forms.MessageBox]::Show('家具实例上限为254。')|Out-Null;return};$used=@($ctx.Furniture|ForEach-Object{[int]$_.index});$idx=1;while($used-contains$idx){$idx++};$x=$byFurniture[$c];[void]$ctx.Furniture.Add([pscustomobject]@{code=$c;index=$idx;placed=$false;type=[byte]$x.type;x=400;y=300;z=0;mirror=0});&$refreshFurniture}).GetNewClosure());$fd.add_Click(({ if(-not$fog.CurrentRow){return};$idx=[int]$fog.CurrentRow.Cells['实例'].Value;$r=@($ctx.Furniture|Where-Object{$_.index-eq$idx})[0];if($r){[void]$ctx.Furniture.Remove($r);&$refreshFurniture}}).GetNewClosure())

    # Cards
    $cTab=New-Object Windows.Forms.TabPage;$cTab.Text='卡片管理';$Tabs.TabPages.Add($cTab);$cos=New-Object Windows.Forms.TextBox;$cos.Location='15,15';$cos.Size='350,26';$cTab.Controls.Add($cos);$cas=New-Object Windows.Forms.TextBox;$cas.Location='555,15';$cas.Size='350,26';$cTab.Controls.Add($cas);$cog=New-InventoryAdminGrid $cTab 15 50 430 650;$cag=New-InventoryAdminGrid $cTab 555 50 525 650
    $cot=New-InventoryAdminTable @('名称','ID','数量');$cov=New-Object Data.DataView;$cov.Table=$cot;$cog.DataSource=$cov;$cat=New-InventoryAdminTable @('名称','ID','说明','效果','产物');foreach($x in $catalog.cards){[void]$cat.Rows.Add($x.name,[string]$x.id,$x.description,$x.effect,$x.result)};$cav=New-Object Data.DataView;$cav.Table=$cat;$cag.DataSource=$cav
    $refreshCards={ $cot.Rows.Clear();foreach($r in $ctx.Cards){$x=$byCard[[uint32]$r.code];[void]$cot.Rows.Add($(if($x){$x.name}else{"未收录卡片（只读保留）-$($r.code)"}),[string]$r.code,[string]$r.count)} }.GetNewClosure();&$refreshCards
    $cqty=New-Object Windows.Forms.NumericUpDown;$cqty.Minimum=1;$cqty.Maximum=255;$cqty.Value=1;$cqty.Location='465,235';$cqty.Size='75,28';$cTab.Controls.Add($cqty);$ca=New-Object Windows.Forms.Button;$ca.Text='← 增加';$ca.Location='460,275';$ca.Size='80,34';$cTab.Controls.Add($ca);$caa=New-Object Windows.Forms.Button;$caa.Text='全部添加';$caa.Location='450,375';$caa.Size='95,34';$cTab.Controls.Add($caa);$ctx.CardAddAllButton=$caa;$car=New-Object Windows.Forms.Button;$car.Text='移除已知卡';$car.Location='450,425';$car.Size='95,34';$car.BackColor=[Drawing.Color]::MistyRose;$cTab.Controls.Add($car);$ctx.CardRemoveAllButton=$car;$cd=New-Object Windows.Forms.Button;$cd.Text='减少/删除 →';$cd.Location='450,325';$cd.Size='95,34';$cTab.Controls.Add($cd);$cos.add_TextChanged(({Set-InventoryAdminFilter $cov $cos.Text @('名称','ID')}).GetNewClosure());$cas.add_TextChanged(({Set-InventoryAdminFilter $cav $cas.Text @('名称','ID','说明','效果','产物')}).GetNewClosure())
    $ca.add_Click(({ $c=Get-InventoryAdminCode $cag;if(-not$c){return};$r=@($ctx.Cards|Where-Object{$_.code-eq$c})[0];if($r){$r.count=[math]::Min(255,[int]$r.count+[int]$cqty.Value)}else{[void]$ctx.Cards.Add([pscustomobject]@{code=$c;count=[uint32]$cqty.Value})};&$refreshCards}).GetNewClosure());$caa.add_Click(({ $existing=@{};foreach($r in $ctx.Cards){$existing[[uint32]$r.code]=$r};foreach($x in $catalog.cards){$c=[uint32]$x.id;$r=$existing[$c];if($r){$r.count=[math]::Min(255,[int]$r.count+[int]$cqty.Value)}else{$r=[pscustomobject]@{code=$c;count=[uint32]$cqty.Value};[void]$ctx.Cards.Add($r);$existing[$c]=$r}};&$refreshCards}).GetNewClosure());$car.add_Click(({Remove-InventoryAdminKnownCards $ctx.Cards $byCard;&$refreshCards}).GetNewClosure());$cd.add_Click(({ $c=Get-InventoryAdminCode $cog;if(-not$c){return};if(-not$byCard.ContainsKey([uint32]$c)){[Windows.Forms.MessageBox]::Show('该卡片未收录在编辑目录中，按原存档只读保留。','只读卡片')|Out-Null;return};$r=@($ctx.Cards|Where-Object{$_.code-eq$c})[0];if($r){$r.count=[int]$r.count-[int]$cqty.Value;if($r.count-le0){[void]$ctx.Cards.Remove($r)};&$refreshCards}}).GetNewClosure())
    $ctx.RefreshAll={&$refreshClothing;&$refreshPets;&$refreshGame;&$refreshFurniture;&$refreshCards}.GetNewClosure()
    foreach($adminTab in @($tab,$petTab,$gameTab,$fTab,$cTab)){Add-InventoryAdminProfileSelector $adminTab $ctx}
    return $ctx
}

function Save-InventoryAdminState($Context,[string]$NameHex,$Shop,$Profile=$null,[switch]$AsSidecar,[switch]$Clone){
    if(-not$NameHex){$NameHex=$Context.NameHex};if(-not$Profile){$Profile=$Context.Profile}
    $state=[ordered]@{version=2;profile=$Profile;shop=$Shop;clothing=@($Context.Clothing);pets=@($Context.Pets|ForEach-Object{[ordered]@{code=[uint32]$_.code;upgrade_material=[uint32]$_.upgrade_material;gems=@([uint32]$_.gems[0],[uint32]$_.gems[1],[uint32]$_.gems[2])}});game_items=@($Context.GameItems|ForEach-Object{[ordered]@{code=[uint32]$_.code;count=[uint32]$_.count;carrier=[string]$_.carrier}});furniture=@($Context.Furniture);cards=@($Context.Cards|ForEach-Object{[ordered]@{code=[uint32]$_.code;count=[uint32]$_.count}})}
    $tmp=Write-InventoryAdminTempJson $state
    try{$command=if($Clone){'clone'}else{'apply'};$args=@($Context.Backend,$command,'--root',$Context.Root,'--name-hex',$NameHex,'--input',$tmp);if($Clone){$args+=@('--source-name-hex',$Context.NameHex);if($null-ne$Context.CharacterId){$args+=@('--source-character-id',[string]$Context.CharacterId)}};if(-not$Clone-and-not$AsSidecar-and$null-ne$Context.CharacterId){$args+=@('--character-id',[string]$Context.CharacterId)};$out=Invoke-InventoryAdminPython $args;return ($out|ConvertFrom-Json)}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}
}

function Test-InventoryAdminInstallation([string]$Root){
    $backend=Join-Path $Root 'gui_launcher\inventory_admin_backend.py';$summary=Get-Content -LiteralPath (Join-Path $Root 'gui_launcher\data\inventory_catalog_summary.json') -Raw -Encoding UTF8|ConvertFrom-Json
    if([int]$summary.counts.'inventory_clothing.json'-ne3885-or[int]$summary.counts.'inventory_pets.json'-ne868-or[int]$summary.counts.'inventory_pet_gems.json'-ne18931-or[int]$summary.counts.'inventory_furniture.json'-ne781-or[int]$summary.counts.'inventory_cards.json'-ne420){throw '物品目录计数校验失败。'}
    return Invoke-InventoryAdminPython @($backend,'selftest','--root',$Root)
}
